// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	CreatedBy   uuid.UUID
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int32
	StockLevel  sql.NullInt32
	CategoryID  uuid.NullUUID
	SupplierID  uuid.NullUUID
	Sku         sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Supplier struct {
	ID          uuid.UUID
	Name        string
	Email       sql.NullString
	Description sql.NullString
	Phone       sql.NullString
	Country     sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Username          string
	Email             string
	Password          string
	Role              string
	ProfilePictureUrl sql.NullString
	Name              string
}
